/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MeuPrimeiroProjeto;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("Ola, mundo");
        System.out.println("Meu segundo comando!");
        
        //Comentário de linha
        
        /*
            Bloco de comentário
            primeira linha
            segunda linha...
        */
        
        /** 
        
            Comentário de documentação,
            utilizado para expotar como doc
        
        */
    }
}
